"use client";
import { useState } from "react";
import { saveQuote } from "@/services/service-quotes/actions";
import type { ServiceQuote } from "@/types/service-quote";
type Item={item_type:string;description:string;quantity:number;unit_price:number;is_optional:boolean};
export function QuoteForm({requestId,providerId,initial}:{requestId:string;providerId:string;initial?:ServiceQuote|null}){
 const [items,setItems]=useState<Item[]>(initial?.items.map(i=>({item_type:i.itemType,description:i.description,quantity:i.quantity,unit_price:i.unitPrice,is_optional:i.isOptional}))??[{item_type:"labor",description:"",quantity:1,unit_price:0,is_optional:false}]);
 const total=items.reduce((n,i)=>n+i.quantity*i.unit_price,0); const update=(index:number,patch:Partial<Item>)=>setItems(current=>current.map((item,i)=>i===index?{...item,...patch}:item));
 return <form action={saveQuote} className="space-y-4"><input type="hidden" name="requestId" value={requestId}/><input type="hidden" name="providerId" value={providerId}/><input type="hidden" name="itemsJson" value={JSON.stringify(items)}/>{items.map((item,i)=><div key={i} className="grid gap-2 rounded-lg border p-3 sm:grid-cols-5"><select value={item.item_type} onChange={e=>update(i,{item_type:e.target.value})}><option value="labor">Mão de obra</option><option value="part">Peça</option><option value="service">Serviço</option><option value="additional">Adicional</option></select><input className="sm:col-span-2" required placeholder="Descrição" value={item.description} onChange={e=>update(i,{description:e.target.value})}/><input type="number" min="0.01" step="0.01" value={item.quantity} onChange={e=>update(i,{quantity:Number(e.target.value)})}/><input type="number" min="0" step="0.01" value={item.unit_price} onChange={e=>update(i,{unit_price:Number(e.target.value)})}/><label><input type="checkbox" checked={item.is_optional} onChange={e=>update(i,{is_optional:e.target.checked})}/> Opcional</label><button type="button" onClick={()=>setItems(x=>x.filter((_,j)=>j!==i))}>Remover</button></div>)}<button type="button" onClick={()=>setItems(x=>[...x,{item_type:"part",description:"",quantity:1,unit_price:0,is_optional:false}])}>+ Adicionar item</button><div className="grid gap-3 sm:grid-cols-2"><input name="estimatedDuration" defaultValue={initial?.estimatedDuration??""} placeholder="Prazo estimado"/><input name="validUntil" defaultValue={initial?.validUntil??""} type="date"/><textarea name="technicalNotes" defaultValue={initial?.technicalNotes??""} placeholder="Observações técnicas"/><textarea name="customerSummary" defaultValue={initial?.customerSummary??""} placeholder="Resumo para a cliente"/><textarea name="warrantyText" defaultValue={initial?.warrantyText??""} placeholder="Garantia"/></div><p className="font-semibold">Prévia: {total.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})} — o banco recalculará o total.</p><div className="flex gap-3"><button name="intent" value="draft" className="rounded bg-slate-200 px-4 py-2">Salvar rascunho</button><button name="intent" value="submit" className="rounded bg-teal-700 px-4 py-2 text-white">Enviar para aprovação</button></div></form>;
}
