import Link from "next/link";
import type { Route } from "next";
import { DemoShell } from "@/components/demo/demo-shell";
import { Card, CardContent } from "@/components/ui/card";
import { listActiveProviders } from "@/services/service-providers";
import { listProviderServiceRequests } from "@/services/service-requests";
import { requireRole } from "@/services/auth/profile";
const formatter = new Intl.DateTimeFormat("pt-BR", { timeZone: "America/Sao_Paulo", dateStyle: "short", timeStyle: "short" });
export default async function ProviderPortalPage({ searchParams }: { searchParams: Promise<{ provider?: string }> }) { const profile=await requireRole(["provider","admin"]); const { provider: queryProvider } = await searchParams; const providers = profile.role==="admin" ? await listActiveProviders() : []; const providerId=profile.role==="provider"?profile.providerId:queryProvider; const selected=profile.role==="admin"?providers.find(item=>item.id===providerId):providerId?{id:providerId}:null; const requests = selected ? await listProviderServiceRequests(selected.id) : []; return <DemoShell><section className="mx-auto max-w-5xl px-5 py-10"><p className="text-sm font-semibold uppercase tracking-wider text-teal-700">Portal do prestador</p><h1 className="mt-2 text-3xl font-semibold">Atendimentos de {profile.displayName}</h1>{profile.role==="admin"&&<form method="get" className="mt-6 flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:flex-row"><select name="provider" defaultValue={providerId ?? ""} className="h-11 flex-1 rounded-lg border border-slate-200 px-3" required><option value="" disabled>Selecione um prestador</option>{providers.map((provider) => <option key={provider.id} value={provider.id}>{provider.name} · {provider.city}</option>)}</select><button className="h-11 rounded-lg bg-teal-700 px-5 font-semibold text-white">Visualizar</button></form>}<div className="mt-8 grid gap-4">{selected && !requests.length && <Card><CardContent className="p-8 text-center text-slate-500">Nenhum atendimento indicado para este prestador.</CardContent></Card>}{requests.map((request) => <Link key={request.id} href={`/demo/prestador/atendimento/${request.id}${profile.role==="admin"?`?provider=${selected?.id}`:""}` as Route}><Card className="hover:border-teal-300"><CardContent className="grid gap-3 p-5 sm:grid-cols-3 sm:items-center"><div><p className="font-mono text-sm font-semibold text-teal-800">{request.referenceCode}</p><p className="font-medium">{request.vehicleBrand} {request.vehicleModel}</p></div><div className="text-sm"><p>{request.city} · {(request.probableCategory ?? "outro").replaceAll("_", " ")}</p><p className="capitalize text-slate-500">{request.perceivedUrgency} · {request.serviceStage.replaceAll("_", " ")}</p></div><p className="text-sm text-slate-500 sm:text-right">{request.providerAssignedAt ? formatter.format(new Date(request.providerAssignedAt)) : "—"}</p></CardContent></Card></Link>)}</div></section></DemoShell>; }
