import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { Card, CardContent } from "@/components/ui/card";
import { DemoShell } from "@/components/demo/demo-shell";
import { getCustomerServiceRequest } from "@/services/service-requests";
import { createSupabaseServerClient } from "@/services/supabase/server";
import { getActiveProvider } from "@/services/service-providers";
import { decideQuote, getQuoteForRequest } from "@/services/service-quotes";
import { submitRating } from "@/services/service-completion";

const timeline = ["Solicitado", "Concierge aceitou", "Prestador indicado", "Aguardando aprovação", "Em execução", "Concluído"];

export default async function ServiceRequestPage({ params }: { params: Promise<{ id: string }> }) {
  const supabase = await createSupabaseServerClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login");
  const { id } = await params; const request = await getCustomerServiceRequest(id); if (!request) notFound();
  const stages = ["solicitado", "concierge_aceitou", "prestador_indicado", "aguardando_aprovacao", "em_execucao", "concluido"];
  const currentStage = Math.max(0, stages.indexOf(request.serviceStage));
  const provider = request.providerId ? await getActiveProvider(request.providerId) : null;
  const quote = await getQuoteForRequest(id);
  return <DemoShell><section className="mx-auto max-w-4xl px-5 py-10 sm:py-14"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-sm font-semibold text-teal-800">{request.referenceCode}</p><h1 className="mt-2 text-3xl font-semibold">{request.serviceStage === "concluido" ? "Seu atendimento foi concluído" : request.serviceStage === "solicitado" ? "Seu atendimento foi solicitado" : "Seu atendimento está em acompanhamento"}</h1></div><span className="w-fit rounded-full bg-teal-100 px-4 py-2 text-sm font-semibold capitalize text-teal-900">{request.serviceStage.replaceAll("_", " ")}</span></div>
    <div className="mt-8 grid gap-5 lg:grid-cols-[1.4fr_0.8fr]"><div className="space-y-5"><Card><CardContent className="space-y-5 p-6"><Info label="Veículo" value={`${request.vehicleBrand} ${request.vehicleModel}${request.vehicleYear ? ` · ${request.vehicleYear}` : ""}`} /><Info label="Cidade" value={request.city} /><Info label="Seu relato" value={request.customerReport} /></CardContent></Card>{provider && <Card className="border-teal-200 bg-teal-50"><CardContent className="space-y-3 p-6"><h2 className="text-lg font-semibold">Prestador indicado</h2><Info label="Prestador" value={provider.name} /><Info label="Cidade" value={provider.city} /></CardContent></Card>}{quote&&quote.status!=="draft"&&<CustomerQuote quote={quote} requestId={id} providerName={provider?.name??"Prestador VERAH"}/>}{request.serviceStage==="concluido"&&<Card className="border-teal-200"><CardContent className="space-y-4 p-6"><h2 className="text-xl font-semibold">Atendimento concluído</h2><p>A VERAH acompanhou seu atendimento do início ao fim.</p>{request.completionNotes&&<Info label="Observações finais" value={request.completionNotes}/>}<Info label="Data de conclusão" value={request.completedAt?new Intl.DateTimeFormat("pt-BR",{timeZone:"America/Sao_Paulo",dateStyle:"short",timeStyle:"short"}).format(new Date(request.completedAt)):"—"}/>{request.customerRating?<div className="rounded bg-emerald-50 p-3"><p className="font-semibold">Sua nota: {request.customerRating}/5</p><p>Obrigada por avaliar sua experiência.</p></div>:<form action={submitRating} className="space-y-3"><input type="hidden" name="requestId" value={request.id}/><label className="block text-sm font-semibold">Nota<select name="rating" className="ml-3 rounded border px-3 py-2" required><option value="5">5 — Excelente</option><option value="4">4 — Muito bom</option><option value="3">3 — Bom</option><option value="2">2 — Regular</option><option value="1">1 — Ruim</option></select></label><textarea name="feedback" className="w-full rounded border p-2" placeholder="Comentário opcional"/><button className="rounded bg-teal-700 px-4 py-2 text-white">Enviar avaliação</button></form>}</CardContent></Card>}<p className="rounded-xl bg-rose-50 p-5 text-sm leading-6 text-rose-900">Nenhuma execução começa sem sua aprovação.</p></div>
      <Card><CardContent className="p-6"><h2 className="text-lg font-semibold">Acompanhamento</h2><ol className="mt-6 space-y-0">{timeline.map((item, index) => <li key={item} className="relative flex gap-3 pb-7 last:pb-0"><span className={`relative z-10 mt-0.5 h-5 w-5 rounded-full border-4 ${index <= currentStage ? "border-teal-200 bg-teal-700" : "border-slate-100 bg-slate-300"}`} />{index < timeline.length - 1 && <span className="absolute left-[9px] top-5 h-full w-px bg-slate-200" />}<div><p className={index <= currentStage ? "font-semibold text-teal-900" : "font-medium text-slate-500"}>{item}</p><p className="mt-1 text-xs text-slate-500">{index <= currentStage ? "Concluído" : "Pendente"}</p></div></li>)}</ol>{request.workOrderId && <Link href={`/work-orders/${request.workOrderId}`} className="mt-5 block rounded-lg border border-teal-200 bg-teal-50 p-3 text-sm font-semibold text-teal-900">Ver Work Order {request.workOrderId} →</Link>}</CardContent></Card>
    </div></section></DemoShell>;
}

function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 whitespace-pre-wrap capitalize leading-6 text-slate-800">{value}</p></div>; }
function CustomerQuote({quote,requestId,providerName}:{quote:NonNullable<Awaited<ReturnType<typeof getQuoteForRequest>>>;requestId:string;providerName:string}){const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});return <Card><CardContent className="space-y-4 p-6"><h2 className="text-xl font-semibold">Seu orçamento está pronto</h2><p>{providerName}</p><p>{quote.customerSummary??"Serviços recomendados conforme avaliação técnica."}</p><div className="space-y-3">{quote.items.map(i=>{const unit=i.itemType==="labor"?"hora":"unidade";return <div key={i.id} className="rounded-lg border p-3 text-sm"><p className="font-semibold">{i.description}</p><p className="text-slate-500">{i.isOptional?"Opcional":"Obrigatório"}</p><p>{i.quantity.toLocaleString("pt-BR")} {unit}{i.quantity===1?"":"s"} × {money(i.unitPrice)}</p><p className="font-medium">Total: {money(i.totalPrice)}</p></div>})}</div><div className="border-t pt-3 text-sm"><p>Mão de obra: {money(quote.laborTotal)}</p><p>Peças: {money(quote.partsTotal)}</p><p>Serviços e adicionais: {money(quote.additionalTotal)}</p><p className="mt-2 text-lg font-semibold">Total geral: {money(quote.totalAmount)}</p></div><Info label="Prazo estimado" value={quote.estimatedDuration??"Não informado"}/><Info label="Garantia" value={quote.warrantyText??"Não informada"}/><Info label="Validade" value={quote.validUntil??"Não informada"}/>{quote.technicalNotes&&<Info label="Observações" value={quote.technicalNotes}/>} {quote.status==="submitted"&&<><p className="rounded-lg bg-amber-50 p-3 text-sm">Você está aprovando o valor total de {money(quote.totalAmount)}. A execução será iniciada somente após esta confirmação.</p><form action={decideQuote} className="space-y-3"><input type="hidden" name="quoteId" value={quote.id}/><input type="hidden" name="requestId" value={requestId}/><textarea name="note" className="w-full rounded border p-2" placeholder="Nota opcional ou pedido de esclarecimento"/><div className="flex gap-3"><button name="intent" value="approve" className="rounded bg-teal-700 px-4 py-2 text-white">Aprovar orçamento</button><button name="intent" value="clarification" className="rounded border px-4 py-2">Solicitar esclarecimento</button></div></form></>}{quote.status!=="submitted"&&<p className="rounded bg-slate-100 p-3 text-sm">Status: {quote.status.replaceAll("_"," ")}{quote.customerDecisionNote?` — ${quote.customerDecisionNote}`:""}</p>}</CardContent></Card>}
